Basepag/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('miapp.urls')),
    path('', include('productos.urls')),
    path('', include('inicioSesion.urls')),
    path('', include('carrito.urls')),
    path('', include('pedidos.urls')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carrito/urls.py
from django.urls import path

from .import views

app_name="carro"

urlpatterns = [
    
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
]

miapp/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', inicio, name="inicio"),
    path('nosotros/', nosotros, name="nosotros"),
    path('soporte/', soporte, name="soporte"),
    path('reportes/', reporte, name="reportes"),
    path('soporte_actualizar/<id_soporte>/', updateSoporte, name="actualizarSoporte"),
    path('soporte_eliminar/<id_soporte>/', deleteSoporte, name="eliminarSoporte"),

    path('editar_perfil/', editarPerfil, name="editar_perfil"),
    path('agregar_avatar/', agregarAvatar, name="agregar_avatar"),

]

productos/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('productos/', productos, name="productos"),
    path('Agregarproductos/', agregar_productos, name="agregarP1"),
    path('buscar/', buscar, name="buscarP1"),
    path('buscarproductos/', buscarProductos, name="buscarProductos"),
    path('producto_actualizar/<id_producto>/', updateProducto, name="actualizarProducto"),
    path('producto_eliminar/<id_producto>/', deleteProducto, name="eliminarProducto"),
]

productos/models.py
from django.db import models
from django import forms

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=1000)
    imagen=models.ImageField(upload_to="productos",null=True, blank=True)
    precio = models.IntegerField()
    disponibilidad =models.BooleanField(default=True)
    
    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"

    def __str__(self):
        return f"{self.nombre}"
    

productos/forms.py
from django import forms
from .models import *

class productosForm(forms.ModelForm):
    nombre = forms.CharField(max_length=50, required=True)
    descripcion = forms.CharField(max_length=250, required=True)
    precio = forms.IntegerField(required=True)
    imagen = forms.ImageField(required=True)
    disponibilidad =forms.BooleanField(required=True)
    class Meta:
        model = Producto
        fields = ['nombre', 'descripcion', 'precio', 'imagen', 'disponibilidad']

productos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from .forms import *

from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView

from django.contrib.auth.decorators import login_required

@login_required
def productos(request):
    productos = Producto.objects.all()
    return render(request, "productos/productos.html", {"productos": productos})

@login_required
def agregar_productos(request):
    if request.method == "POST":
        miForm = productosForm(request.POST, request.FILES)
        if miForm.is_valid():
            miForm.save()
            return redirect('productos')
    else:
        miForm = productosForm() 
    return render(request, "productos/agregarProductos.html", {"form": miForm })

@login_required
def buscar(request):
    return render(request, "productos/buscar.html")

@login_required
def buscarProductos(request):
    buscar_param = request.GET.get("buscarP1")
    if buscar_param:
        productos = Producto.objects.filter(nombre__icontains=buscar_param)
        contexto = {"productos": productos}
        return render(request, "productos/productos.html", contexto)
    else:
        return HttpResponse("No se ingresaron patrones de búsqueda")
    
@login_required
def updateProducto(request, id_producto):
    producto = Producto.objects.get(id=id_producto)
    if request.method == "POST":
        miForm = productosForm(request.POST, request.FILES)
        if miForm.is_valid():
            producto.nombre = miForm.cleaned_data.get('nombre')
            producto.descripcion = miForm.cleaned_data.get('descripcion')
            producto.precio = miForm.cleaned_data.get('precio')
            producto.imagen = miForm.cleaned_data.get('imagen')
            producto.disponibilidad = miForm.cleaned_data.get('disponibilidad')
            producto.save()
            return redirect(reverse_lazy('productos'))   
    else:
        miForm = productosForm(initial={
            'nombre': producto.nombre,
            'descripcion': producto.descripcion,
            'precio': producto.precio,
            'imagen': producto.imagen,
            'disponibilidad': producto.disponibilidad
        })
    return render(request, "productos/actualizarProducto.html", {'form': miForm})

@login_required
def deleteProducto(request, id_producto):
    producto = Producto.objects.get(id=id_producto)
    producto.delete()
    return redirect(reverse_lazy('productos'))

productos/templates/productos/actualizarProducto.html
{% extends 'miapp/home.html' %}

{% block titulo %}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Magnus Lab</h1>
            <p class="lead fw-normal text-white-50 mb-0"></p>
        </div>
    </div>
</header>

{% endblock titulo %}

{% block productos %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">confirmar</button>
</form>
{% endblock productos %}

productos/templates/productos/agregarProductos.html
{% extends 'miapp/home.html' %}

{% block titulo %}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Magnus Lab</h1>
            <p class="lead fw-normal text-white-50 mb-0">Agregar Productos</p>
        </div>
    </div>
</header>

{% endblock titulo %}

{% block productos %}
{% if request.user.is_superuser %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Agregar Producto</button>
</form>
{% else %}
<br/><br/><br/><br/><br/><br/>
<div class="text-center text-black">
    <h5>Tienes que ser un usuario admin para agregar productos<h5>
<div>
<br/>
<br/><br/><br/><br/><br/><br/>
{% endif %}
{% endblock productos %}

productos/templates/productos/buscar.html
{% extends 'miapp/home.html' %}

{% block titulo %}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Magnus Lab</h1>
            <p class="lead fw-normal text-white-50 mb-0">Busqueda de productos</p>
        </div>
    </div>
</header>

{% endblock titulo %}

{% block productos %}

<form action="{% url 'buscarProductos' %}" method="get">
    {% csrf_token %}
    <br>
    <p>Busqueda: <input type="text" name="buscarP1" id="buscarP1"></p>
    <input type="submit" value="Buscar">
</form>

{% endblock productos %}

productos/templates/productos/productos.html
{% extends 'miapp/home.html' %}

{% block titulo %}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Magnus Lab</h1>
            <p class="lead fw-normal text-white-50 mb-0">Productos veterinarios</p>
        </div>
    </div>
</header>

{% endblock titulo %}


{% block productos %}

<div class="container">

    <div style="float:right;">

            {% include "productos/widget.html" %}
            
    </div>

<div class="row">

{% for producto in productos %}
<section class="py-5">
    <div class="card-body p-4">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                <div class="card" style="width: 30%; margin: 5px 5px;">
                    <img src="{{producto.imagen.url}}" class="card-img-top">
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{producto.nombre}}</h5>
                            {{producto.descripcion}}<br>
                            {% if producto.disponibilidad %}
                            Disponible<br>
                            {% else %}
                            No Disponible<br>
                            {% endif %}
                            <!-- Product price-->
                            {{producto.precio}}&nbsp;$
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al carro</a>
                    </div>
                    {% if request.user.is_superuser %}
                    <a
                    href="{% url 'actualizarProducto' producto.id %}"
                    class="btn btn-primary"
                    style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                    ><i class="fa fa-edit fa-sm" title="Edit Record"></i>
                </a>
                <br>
                <a
                    href="{% url 'eliminarProducto' producto.id %}"
                    class="btn btn-danger"
                    style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .75rem; --bs-btn-font-size: .75rem;"
                ><i class="fa fa-trash fa-sm" title="Delete Record"></i>
                </a>      
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>


{% endfor %}

{% endblock productos %}

</div>

productos/templates/productos/tienda.html
{% extends "ProyectoWebApp/base.html" %}

{% load static %}

{% block content %}

<div class="container">

  <div style="float:right;">       
 

    {% if request.user.is_authenticated %}
 
      {% include "carro/widget.html" %}

    {% else %} 

      <div class="alert alert-danger text-center">Login para ver Carro</div>     

    {% endif %}
    

  </div>


  <div class="row">

{% for producto in productos %}

    <div class="col-md-3">

    <div class="card" style="width: 100%; margin: 5px 5px;">

        <img src="{{producto.imagen.url}}" class="card-img-top">

        <div class="card-body" style="text-align: center;">

            <h7 class="card-title">{{producto.nombre}}</h7>

            <p class="card-text">{{producto.precio}}&nbsp;€</p>


        </div> 
        
        <div class="card-footer text-center">

            <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al carro</a>

        </div>

    </div><!--card que se cierra-->
    
  </div>



{% endfor %}
  </div>
 
  
</div>

{% endblock %}

productos/templates/productos/widget.html
<table class="table table-bordered" style="color: black;">

    <thead>

        <tr>

            <th colspan="3" class="text-center">

                Carro compras


            </th>



        </tr>

    </tr>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Suma</th>


    </tr>
    </thead>

    <tbody>
        {% if request.session.carro.items %}

            {% for key, value in request.session.carro.items %}

              <tr class="text-center">

                <td>{{value.nombre}}</td>
                <td>{{value.cantidad}}</td>
                <td>

                    <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                    <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
                    <br/>

                    {{value.precio}} $

                </td>

              </tr>  
            {% endfor %}

            {% else %}

            <tr>

                <td colspan="3">
                    <div class="alert alert-danger text-center">

                        Sin productos
                    </div>
                </td>


            </tr>



            {% endif %}
    </tbody>

    <tfoot>

        
        <tr>

            <td colspan="3">

                Total: {{importe_total_carro}} $

            </td>

        </tr>
        {% if request.session.carro.items %}
        <tr><td colspan="3" style="text-align: center;">

            <a href="../pedidos" class="btn btn-success">Hacer Pedido</a>

        </td></tr>
        {% endif %}

    </tfoot>

</table>